name: Deploy # 部署

on: # 触发条件
  push:
    branches:
      - main # 推送到 main 分支（这里的分支名很重要，不要弄错了）

  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout # Checkout 仓库
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node # 安装 Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install Hexo # 安装 Hexo
        run: |
          npm install hexo-cli -g
          
      - name: Cache Modules # 缓存 Node 插件
        uses: actions/cache@v1
        id: cache-modules
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
      
      - name: Install Dependencies # 如果没有缓存或 插件有更新，则安装插件
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: | # **如果仓库里没有 package-lock.json，上传一下，npm ci 必须要有 package-lock.json**
          npm ci
          
      - name: Generate # 生成
        run: |
          hexo clean
          hexo generate
          
      - name: Deploy # 部署
        run: |
          git config --global user.name '${{ secrets.GITHUBUSERNAME }}'
          git config --global user.email '${{ secrets.GITHUBEMAIL }}'
          git clone https://github.com/GC-ZF/GC-ZF.github.io.git .deploy_git
          export TZ='Asia/Shanghai'
          hexo deploy

      - name: push VPS # 部署到云服务器
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.USER_HOST }}
          user: ${{ secrets.USER_NAME }}
          pass: ${{ secrets.USER_PASS }}
          connect_timeout: 10s
          local: './.deploy_git/*'
          remote: ${{ secrets.VPSSITE }}


作者: 张时贰
链接: https://zhangshier.vip/posts/8779/
来源: 张时贰
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。